### ISSUE TITLE
Can you please explain how the model embeddings were generated?

### ISSUE THREAD

**Issue by nlama-cls** [deepathology/fseg#5]
It is not clear how 1D features are computed before clustering, did you apply GAP operation on patch tokens (for example, 1x256x1024 shape for UNI) only or all tokens including class token (1x257x1024 shape for UNI)? Did you use the raw features directly from the model for the clustering? Thank you.

**Comment by jacobgil** [comment]
We used the same reshape transform that appears in the readme,
```python
class TransformerReshapeTransform:
    def __init__(self):
        self.input_tensor_shape = None

    def __call__(self, tensor):
        result = torch.nn.ReLU()(tensor[:, 1:, :].reshape(tensor.size(0),
                                self.input_tensor_shape[2] // 16,
                                self.input_tensor_shape[3] // 16,
                                tensor.size(2)))
        # Bring the channels to the first dimension, like in CNNs.
        result = result.transpose(2, 3).transpose(1, 2)
        return result
```

But then spatially averaged the result, to get a 1D embedding, for extracted patches.
These 1D embeddings were then clustered, and then we took the cluster centers.

**Comment by nlama-cls** [comment]
Perfect, thanks!
